{% set name = "dcor" %}
{% set version = "0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dcor-{{ version }}.tar.gz
  sha256: f5d39776101db4787348e6be6cd9369341efeb40b070509a30d5c57185558431

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - array_api_compat
    - numba >=0.51
    - numpy
    - python >={{ python_min }},<4.0
    - scipy
    - setuptools
    - joblib

test:
  imports:
    - dcor
    - dcor.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vnmabus/dcor
  summary: 'dcor: distance correlation and related E-statistics in Python.'
  license: MIT
  license_file: LICENSE
  description: |
    This package offers functions for calculating several E-statistics
    such as:
    - Estimator of the energy distance.
    - Biased and unbiased estimators of distance covariance and
    distance correlation.
    - Estimators of the partial distance covariance and partial
    distance covariance.
    It also provides tests based on these E-statistics:
    - Test of homogeneity based on the energy distance.
    - Test of independence based on distance covariance.
  doc_url: https://dcor.readthedocs.io/
  dev_url: https://github.com/vnmabus/dcor

extra:
  recipe-maintainers:
    - vnmabus
