{% set name = "dcor" %}
{% set version = "0.5.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dcor-{{ version }}.tar.gz
  sha256: 8597329226d83d9b89e8bc15f9cb697524ed038505e4b519f7c8c895a68a14b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - numba >=0.51
    - numpy
    - python >=3.6,<4.0
    - scipy
    - setuptools
    - joblib

test:
  imports:
    - dcor
    - dcor.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vnmabus/dcor
  summary: 'dcor: distance correlation and related E-statistics in Python.'
  license: MIT
  license_file: LICENSE
  description: |
    This package offers functions for calculating several E-statistics
    such as:
    - Estimator of the energy distance.
    - Biased and unbiased estimators of distance covariance and
    distance correlation.
    - Estimators of the partial distance covariance and partial
    distance covariance.
    It also provides tests based on these E-statistics:
    - Test of homogeneity based on the energy distance.
    - Test of independence based on distance covariance.
  doc_url: https://dcor.readthedocs.io/
  dev_url: https://github.com/vnmabus/dcor

extra:
  recipe-maintainers:
    - vnmabus
